### ISSUE TITLE
AttributeError: 'AppendDemoInfo' object has no attribute 'reset_to_demo'

### ISSUE THREAD

**Issue by chenzixuan99** [MohitShridhar/genima#1]
Thanks for sharing such an awesome project!

I am getting the error:
```
Traceback (most recent call last).
  File "/data3/czx/genima/controller/eval_genima.py", line 409, in main
    workspace.eval()
  File "/data3/czx/genima/controller/eval_genima.py", line 382, in eval
    self.eval_checkpoints(eval_ckpts)
  File "/data3/czx/genima/controller/eval_genima.py", line 142, in eval_checkpoints
    _, obs = self.eval_env.reset_to_demo(idx=run_episode)
AttributeError: 'AppendDemoInfo' object has no attribute 'reset_to_demo'
```

when I run the following command after collecting data:

```
python eval_genima.py \
     task=open_box \
     dataset_root=/data3/share/genima_data/val_data \
     diffusion_ckpt=/data3/share/genima_data/ckpts/25_tasks/diffusion_sdturbo_R256x4_tiled \
     controller_ckpt=/data3/share/genima_data/ckpts/25_tasks/controller_act \
     num_eval_episodes=10 \
     save_gen_image=True \
     num_diffusion_steps=5 \
     execution_horizon=20 \
     save_video=True \
     wandb.use=True \
     eval_type=latest \
     headless=False
```

Is there any good suggestion to solve this problem? Thanks!

**Comment by MohitShridhar** [comment]
@albzni, unfortunately I don't have a linux machine to debug this 😢

can you try replacing L142 in eval_genima.py with
`_, obs = self.eval_env.unwrapped.reset_to_demo(idx=run_episode)`
the key thing is `.unwrapped`

**Comment by chenzixuan99** [comment]
> @albzni, unfortunately I don't have a linux machine to debug this 😢
> 
> can you try replacing L142 in eval_genima.py with `_, obs = self.eval_env.unwrapped.reset_to_demo(idx=run_episode)` the key thing is `.unwrapped`

it works! Thanks for your reply.😊

**Comment by MohitShridhar** [comment]
@albzni, great! 

Pushed the fix.
